In [ ]:
import numpy as np

In [ ]:
matrix_1 = np.array([[2,4],[3,4]])

In [ ]:
print(matrix_1)

[[2 4]
 [3 4]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[2,4,21],[3,4,31],[6,4,34]])

print(matrix_2)

[[ 2  4 21]
 [ 3  4 31]
 [ 6  4 34]]


In [ ]:
matrix_2.shape

(3, 3)

Creating Matrix with random values


In [ ]:
random_matrix = np.random.rand(3,3)

print(random_matrix)

[[0.73985284 0.13452619 0.94108803]
 [0.1461382  0.62282182 0.2245371 ]
 [0.32686863 0.74591004 0.57938021]]


Creating Random matrix with integers

In [ ]:
random_matrix = np.random.randint(120,size=(4,4))

print(random_matrix)

[[  7  44  36  54]
 [105  27 119  45]
 [ 46  18 102 117]
 [  3  31  89  12]]


Matrix with all values =1

In [ ]:
matrix_3 = np.ones((3,3))

print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((3,3), dtype=int)

print(matrix_3)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
matrix_4 = np.zeros((3,3))

print(matrix_4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
matrix_4 = np.zeros((4,7),dtype=int)

print(matrix_4)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


Identity Matrixx


In [ ]:
identity_matrix = np.eye(5,5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose Of A Matrix

In [ ]:
a = np.random.randint(100, size=(4,5))

print(a)

[[ 2 15 25 62  5]
 [25 66 34  4 95]
 [61 72 53 27 89]
 [11 88 45 50 27]]


In [ ]:
transpose_of_a_matrix = np.transpose(a)

print(transpose_of_a_matrix)

[[ 2 25 61 11]
 [15 66 72 88]
 [25 34 53 45]
 [62  4 27 50]
 [ 5 95 89 27]]


## Determinants

In [ ]:
a = np.random.randint(100, size=(3,3))

print(a)

[[77 26  6]
 [29 69 31]
 [68 91 60]]


In [ ]:
a[1][0]

29

### **Determinant 2x2 Matrix**

In [ ]:
def det_2x2(matrix_2x2):
  det=(matrix_2x2[0][0]*matrix_2x2[1][1]) - (matrix_2x2[0][1]*matrix_2x2[1][0])
  return det

In [ ]:
a = np.array([[1,2],[3,4]])

print(det_2x2(a))

-2


### **Determinant 3x3 Matrix**

In [ ]:
def det_3x3(matrix_3x3):
  #Expanding By Row-1
  i = np.array([[matrix_3x3[1][1],matrix_3x3[1][2]],[matrix_3x3[2][1],matrix_3x3[2][2]]])
  j = np.array([[matrix_3x3[1][0],matrix_3x3[1][2]],[matrix_3x3[2][0],matrix_3x3[2][2]]])
  k = np.array([[matrix_3x3[1][0],matrix_3x3[1][1]],[matrix_3x3[2][0],matrix_3x3[2][1]]])

  det = (matrix_3x3[0][0]*det_2x2(i))-(matrix_3x3[0][1]*det_2x2(j))+(matrix_3x3[0][2]*det_2x2(k))
  return det

In [ ]:
a = np.array([[2,4,21],[3,4,31],[6,4,34]])

print(det_3x3(a))

108


In [ ]:
# Create a NumPy matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Index of the column you want to remove
col_to_remove = 1

# Remove the specified column
new_matrix = np.delete(matrix, col_to_remove, axis=1)

print("Original matrix:\n", matrix)
print("Matrix after removing column:\n", new_matrix)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after removing column:
 [[1 3]
 [4 6]
 [7 9]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,5,9]])

print(det_3x3(a))

-18


## Adjoint of a Matrix

In [ ]:
def adj(matrix):
  n_matrix = matrix.copy()
  for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
      print("I: ",i, " J: ", j)
      temp_matrix = np.delete(matrix, i,axis=0)
      temp_matrix = np.delete(temp_matrix, j,axis=1)

      print("Temp Matrix is: ",temp_matrix)
      print("Determinant of Matrix ", i,j,"IS : " ,det_2x2(temp_matrix))
      n_matrix[i][j] = ((-1)**(i+j))*det_2x2(temp_matrix)

  return np.transpose(n_matrix)


In [ ]:
adj(a)

I:  0  J:  0
Temp Matrix is:  [[5 6]
 [5 9]]
Determinant of Matrix  0 0 IS :  15
I:  0  J:  1
Temp Matrix is:  [[4 6]
 [7 9]]
Determinant of Matrix  0 1 IS :  -6
I:  0  J:  2
Temp Matrix is:  [[4 5]
 [7 5]]
Determinant of Matrix  0 2 IS :  -15
I:  1  J:  0
Temp Matrix is:  [[2 3]
 [5 9]]
Determinant of Matrix  1 0 IS :  3
I:  1  J:  1
Temp Matrix is:  [[1 3]
 [7 9]]
Determinant of Matrix  1 1 IS :  -12
I:  1  J:  2
Temp Matrix is:  [[1 2]
 [7 5]]
Determinant of Matrix  1 2 IS :  -9
I:  2  J:  0
Temp Matrix is:  [[2 3]
 [5 6]]
Determinant of Matrix  2 0 IS :  -3
I:  2  J:  1
Temp Matrix is:  [[1 3]
 [4 6]]
Determinant of Matrix  2 1 IS :  -6
I:  2  J:  2
Temp Matrix is:  [[1 2]
 [4 5]]
Determinant of Matrix  2 2 IS :  -3


array([[ 15,  -3,  -3],
       [  6, -12,   6],
       [-15,   9,  -3]])

In [ ]:
len(a)

3

In [ ]:
new_list = [[0,0,0],[0,0,0],[0,0,0]]

for i in range(1,3):
  for j in range(1,3):
    new_list[i][j] = i*j

print(new_list)

[[0, 0, 0], [0, 1, 2], [0, 2, 4]]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,5,9]])

print(det_3x3(a))

-18


In [ ]:
def adj(matrix):
  n_matrix = matrix.copy()
  for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
      print("I: ",i, " J: ", j)
      temp_matrix = np.vstack((matrix[:i, :], matrix[i+1:, :]))
      temp_matrix = np.hstack((temp_matrix[:, :j], temp_matrix[:, j+1:]))


      print("Temp Matrix is: ",temp_matrix)
      print("Determinant of Matrix ", i,j,"IS : " ,det_2x2(temp_matrix))
      n_matrix[i][j] = ((-1)**(i+j))*det_2x2(temp_matrix)

  return np.transpose(n_matrix)

In [ ]:
def adj(matrix):
  n_matrix = matrix.copy()
  for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
      # print("I: ",i, " J: ", j)
      temp_matrix = np.vstack((matrix[:i, :], matrix[i+1:, :]))
      temp_matrix = np.hstack((temp_matrix[:, :j], temp_matrix[:, j+1:]))


      # print("Temp Matrix is: ",temp_matrix)
      # print("Determinant of Matrix ", i,j,"IS : " ,det_2x2(temp_matrix))
      n_matrix[i][j] = ((-1)**(i+j))*det_2x2(temp_matrix)

  return np.transpose(n_matrix)

In [ ]:
adj(a)

array([[ 15,  -3,  -3],
       [  6, -12,   6],
       [-15,   9,  -3]])

# **Inverse of a matrix**

inverse of 3x3 matrix

In [ ]:
def inverse_matrix(matrix):
  return adj(matrix)/det_3x3(matrix)

In [ ]:
inverse_matrix(a)

array([[-0.83333333,  0.16666667,  0.16666667],
       [-0.33333333,  0.66666667, -0.33333333],
       [ 0.83333333, -0.5       ,  0.16666667]])

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(det_3x3(b))

inverse_matrix(b)

0


<ipython-input-147-db286cb0879c>:2: RuntimeWarning: divide by zero encountered in divide
  return adj(matrix)/det_3x3(matrix)


array([[-inf,  inf, -inf],
       [ inf, -inf,  inf],
       [-inf,  inf, -inf]])